
WITH AAL_CAMPAIGN_STATS AS (
  SELECT
    BAN,
    SUBSCRIBER_NO AS MSISDN,
    MIN(CAMPAIGN_IN_HOME_DATE) AS EARLIEST_CAMPAIGN_RECEIVED_DT,
    MAX(CAMPAIGN_IN_HOME_DATE) AS LATEST_CAMPAIGN_RECEIVED_DT,
    SUM(DELIVERED) AS TOTAL_DELIVERED_MSGS,
    SUM(OPENED) AS TOTAL_OPENED_MSGS,
    SUM(CLICKTHROUGH) AS TOTAL_CLICKTHROUGH_MSGS,
    SUM(UNSUBSCRIBE) AS TOTAL_UNSUBSCRIBE_EVENTS,
    SUM(SMS_OPT_OUT) AS TOTAL_SMS_OPT_OUT_EVENTS,
    SUM(CONVERSION) AS TOTAL_CONVERSIONS,
    MIN(CONVERSION_DT) AS EARLIEST_CONVERSION_DT,
    MAX(CONVERSION_DT) AS LATEST_CONVERSION_DT
  FROM `cto-wln-sa-data-pr-bb5283.measurements_data.epdmadm_aax_source_2022_ref`
  WHERE CONTROL_GROUP='N'
  GROUP BY BAN, MSISDN

),

AAL_OPENED_STATS AS (
  SELECT
    BAN, 
    SUBSCRIBER_NO AS MSISDN,
    MIN(CAMPAIGN_IN_HOME_DATE) AS EARLIEST_OPENED_DT,
    MAX(CAMPAIGN_IN_HOME_DATE) AS LATEST_OPENED_DT
  FROM `cto-wln-sa-data-pr-bb5283.measurements_data.epdmadm_aax_source_2022_ref`
  WHERE OPENED >= 1 AND CONTROL_GROUP='N'
  GROUP BY BAN,MSISDN
),

AAL_CLICKTHROUGH_STATS AS (
  SELECT
    BAN, 
    SUBSCRIBER_NO AS MSISDN,
    MIN(CAMPAIGN_IN_HOME_DATE) AS EARLIEST_CLICKTHROUGH_DT,
    MAX(CAMPAIGN_IN_HOME_DATE) AS LATEST_CLICKTHROUGH_DT
  FROM `cto-wln-sa-data-pr-bb5283.measurements_data.epdmadm_aax_source_2022_ref`
  WHERE CLICKTHROUGH >= 1 AND CONTROL_GROUP='N'
  GROUP BY BAN,MSISDN
),

AAL_UNSUBSCRIBE_STATS AS (
  SELECT
    BAN, 
    SUBSCRIBER_NO AS MSISDN,
    MIN(CAMPAIGN_IN_HOME_DATE) AS EARLIEST_UNSUBSCRIBE_DT,
    MAX(CAMPAIGN_IN_HOME_DATE) AS LATEST_UNSUBSCRIBE_DT
  FROM `cto-wln-sa-data-pr-bb5283.measurements_data.epdmadm_aax_source_2022_ref`
  WHERE UNSUBSCRIBE >= 1 AND CONTROL_GROUP='N'
  GROUP BY BAN,MSISDN
),

AAL_SMS_OPT_OUT_STATS AS (
  SELECT
    BAN, 
    SUBSCRIBER_NO AS MSISDN,
    MIN(CAMPAIGN_IN_HOME_DATE) AS EARLIEST_SMS_OPT_OUT_DT,
    MAX(CAMPAIGN_IN_HOME_DATE) AS LATEST_SMS_OPT_OUT_DT
  FROM `cto-wln-sa-data-pr-bb5283.measurements_data.epdmadm_aax_source_2022_ref`
  WHERE SMS_OPT_OUT >= 1 AND CONTROL_GROUP='N'
  GROUP BY BAN,MSISDN
),

AAL_SUBSCRIBE_STATS AS (
  SELECT 
    A.BAN,
    A.MSISDN,

    A.TOTAL_DELIVERED_MSGS,
    A.EARLIEST_CAMPAIGN_RECEIVED_DT,
    A.LATEST_CAMPAIGN_RECEIVED_DT,

    A.TOTAL_OPENED_MSGS,
    B.EARLIEST_OPENED_DT,
    B.LATEST_OPENED_DT,
    DATE_DIFF(B.EARLIEST_OPENED_DT, A.EARLIEST_CAMPAIGN_RECEIVED_DT, DAY) AS DAYS_DIFF_OPENED_DELIVERED,

    A.TOTAL_CLICKTHROUGH_MSGS,
    C.EARLIEST_CLICKTHROUGH_DT,
    C.LATEST_CLICKTHROUGH_DT,
    DATE_DIFF(C.EARLIEST_CLICKTHROUGH_DT, A.EARLIEST_CAMPAIGN_RECEIVED_DT, DAY) AS DAYS_DIFF_CLICKTHROUGH_DELIVERED,
    DATE_DIFF(C.EARLIEST_CLICKTHROUGH_DT, B.EARLIEST_OPENED_DT, DAY) AS DAYS_DIFF_CLICKTHROUGH_OPENED,

    A.TOTAL_UNSUBSCRIBE_EVENTS,
    D.EARLIEST_UNSUBSCRIBE_DT,
    D.LATEST_UNSUBSCRIBE_DT,
    DATE_DIFF(D.EARLIEST_UNSUBSCRIBE_DT, A.EARLIEST_CAMPAIGN_RECEIVED_DT, DAY) AS DAYS_DIFF_UNSUBSCRIBE_DELIVERED,
    DATE_DIFF(D.EARLIEST_UNSUBSCRIBE_DT, B.EARLIEST_OPENED_DT, DAY) AS DAYS_DIFF_UNSUBSCRIBE_OPENED,
    DATE_DIFF(D.EARLIEST_UNSUBSCRIBE_DT, C.EARLIEST_CLICKTHROUGH_DT, DAY) AS DAYS_DIFF_UNSUBSCRIBE_CLICKTHROUGH,

    A.TOTAL_SMS_OPT_OUT_EVENTS,
    E.EARLIEST_SMS_OPT_OUT_DT,
    E.LATEST_SMS_OPT_OUT_DT,
    DATE_DIFF(E.EARLIEST_SMS_OPT_OUT_DT, A.EARLIEST_CAMPAIGN_RECEIVED_DT, DAY) AS DAYS_DIFF_SMS_OPT_OUT_DELIVERED,
    DATE_DIFF(E.EARLIEST_SMS_OPT_OUT_DT, B.EARLIEST_OPENED_DT, DAY) AS DAYS_DIFF_SMS_OPT_OUT_OPENED,
    DATE_DIFF(E.EARLIEST_SMS_OPT_OUT_DT, C.EARLIEST_CLICKTHROUGH_DT, DAY) AS DAYS_DIFF_SMS_OPT_OUT_CLICKTHROUGH,

    A.TOTAL_CONVERSIONS,
    A.EARLIEST_CONVERSION_DT,
    A.LATEST_CONVERSION_DT,
    DATE_DIFF(A.EARLIEST_CONVERSION_DT, A.EARLIEST_CAMPAIGN_RECEIVED_DT, DAY) AS DAYS_DIFF_CONVERSION_DELIVERED,
    DATE_DIFF(A.EARLIEST_CONVERSION_DT, B.EARLIEST_OPENED_DT, DAY) AS DAYS_DIFF_CONVERSION_OPENED,
    DATE_DIFF(A.EARLIEST_CONVERSION_DT, C.EARLIEST_CLICKTHROUGH_DT, DAY) AS DAYS_DIFF_CONVERSION_CLICKTHROUGH,   

  FROM AAL_CAMPAIGN_STATS A 
  LEFT JOIN AAL_OPENED_STATS B 
  ON A.BAN = B.BAN AND A.MSISDN = B.MSISDN
  LEFT JOIN AAL_CLICKTHROUGH_STATS C 
  ON A.BAN = C.BAN AND A.MSISDN = C.MSISDN
    LEFT JOIN AAL_UNSUBSCRIBE_STATS D 
  ON A.BAN = D.BAN AND A.MSISDN = D.MSISDN
    LEFT JOIN AAL_SMS_OPT_OUT_STATS E 
  ON A.BAN = E.BAN AND A.MSISDN = E.MSISDN
)


SELECT * FROM AAL_SUBSCRIBE_STATS