-- Get Brand info
WITH brand_table AS (
  SELECT 
    A.*,  
    IFNULL(B.BRAND_TXT, 'Other') AS BRAND_TXT
  FROM `cto-wln-sa-data-pr-bb5283.customer_personas_features.imsi_app_usage_trends_weekly_ts` A
  LEFT JOIN `cto-wln-sa-data-pr-bb5283.ref_table.bq_hpbi_product_instance_profl` B 
  ON A.imsi_num= B.PROD_INSTNC_ALIAS_STR

),

-- Get counts of high data users for category using PERCENT_RANK() 
ranked_data AS (

  SELECT 
    *,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_sports <> 0 THEN usage_volume_MB_entertainment_sports ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_sports_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_realestate_landlord <> 0 THEN usage_volume_MB_realestate_landlord ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_realestate_landlord_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_agriculture_farmmanagement <> 0 THEN usage_volume_MB_agriculture_farmmanagement ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_agriculture_farmmanagement_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_education <> 0 THEN usage_volume_MB_productivity_education ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_education_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_telus <> 0 THEN usage_volume_MB_telecom_telus ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_telus_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_realestate_buysellrent <> 0 THEN usage_volume_MB_realestate_buysellrent ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_realestate_buysellrent_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_trips <> 0 THEN usage_volume_MB_travel_trips ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_trips_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_finance_banking <> 0 THEN usage_volume_MB_finance_banking ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_finance_banking_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_pets_dogs <> 0 THEN usage_volume_MB_pets_dogs ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_pets_dogs_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_lifestyle_mentalhealth <> 0 THEN usage_volume_MB_lifestyle_mentalhealth ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_lifestyle_mentalhealth_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_os_appstore <> 0 THEN usage_volume_MB_os_appstore ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_os_appstore_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_news_generic <> 0 THEN usage_volume_MB_news_generic ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_news_generic_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_music <> 0 THEN usage_volume_MB_entertainment_music ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_music_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_communication_miscellaneous <> 0 THEN usage_volume_MB_communication_miscellaneous ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_communication_miscellaneous_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_gaming_moderate <> 0 THEN usage_volume_MB_gaming_moderate ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_gaming_moderate_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_utility_security <> 0 THEN usage_volume_MB_utility_security ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_utility_security_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_communication_socialmedia <> 0 THEN usage_volume_MB_communication_socialmedia ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_communication_socialmedia_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_other <> 0 THEN usage_volume_MB_productivity_other ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_other_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_shopping_fashion <> 0 THEN usage_volume_MB_shopping_fashion ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_shopping_fashion_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_webbrowser <> 0 THEN usage_volume_MB_productivity_webbrowser ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_webbrowser_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_finance_utilities <> 0 THEN usage_volume_MB_finance_utilities ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_finance_utilities_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_travel <> 0 THEN usage_volume_MB_travel_travel ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_travel_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_lifestyle_fitness <> 0 THEN usage_volume_MB_lifestyle_fitness ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_lifestyle_fitness_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_finance_business <> 0 THEN usage_volume_MB_finance_business ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_finance_business_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_lifestyle_relationships <> 0 THEN usage_volume_MB_lifestyle_relationships ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_lifestyle_relationships_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_wireline <> 0 THEN usage_volume_MB_telecom_wireline ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_wireline_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_lodging <> 0 THEN usage_volume_MB_travel_lodging ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_lodging_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_editingsoftware <> 0 THEN usage_volume_MB_productivity_editingsoftware ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_editingsoftware_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_pets_petssupplies <> 0 THEN usage_volume_MB_pets_petssupplies ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_pets_petssupplies_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_ridehailing <> 0 THEN usage_volume_MB_travel_ridehailing ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_ridehailing_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_agriculture_farmassociations <> 0 THEN usage_volume_MB_agriculture_farmassociations ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_agriculture_farmassociations_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_professional <> 0 THEN usage_volume_MB_productivity_professional ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_professional_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_smarthome_automation <> 0 THEN usage_volume_MB_smarthome_automation ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_smarthome_automation_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_lifestyle_healthcare <> 0 THEN usage_volume_MB_lifestyle_healthcare ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_lifestyle_healthcare_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_tvandmovies <> 0 THEN usage_volume_MB_entertainment_tvandmovies ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_tvandmovies_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_flights <> 0 THEN usage_volume_MB_travel_flights ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_flights_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_gaming_casual <> 0 THEN usage_volume_MB_gaming_casual ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_gaming_casual_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_finance_paymentapps <> 0 THEN usage_volume_MB_finance_paymentapps ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_finance_paymentapps_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_gaming_kids <> 0 THEN usage_volume_MB_gaming_kids ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_gaming_kids_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_navigation <> 0 THEN usage_volume_MB_travel_navigation ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_navigation_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_utility_devicecare <> 0 THEN usage_volume_MB_utility_devicecare ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_utility_devicecare_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_wirelesswireline <> 0 THEN usage_volume_MB_telecom_wirelesswireline ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_wirelesswireline_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_news <> 0 THEN usage_volume_MB_entertainment_news ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_news_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_others <> 0 THEN usage_volume_MB_telecom_others ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_others_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_news_weather <> 0 THEN usage_volume_MB_news_weather ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_news_weather_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_radio <> 0 THEN usage_volume_MB_entertainment_radio ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_radio_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_airport <> 0 THEN usage_volume_MB_travel_airport ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_airport_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_live <> 0 THEN usage_volume_MB_entertainment_live ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_live_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_pricecomparison <> 0 THEN usage_volume_MB_telecom_pricecomparison ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_pricecomparison_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_pets_other <> 0 THEN usage_volume_MB_pets_other ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_pets_other_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_lifestyle_identification <> 0 THEN usage_volume_MB_lifestyle_identification ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_lifestyle_identification_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_realestate_projectmanagement <> 0 THEN usage_volume_MB_realestate_projectmanagement ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_realestate_projectmanagement_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_communication_talking <> 0 THEN usage_volume_MB_communication_talking ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_communication_talking_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_network_security <> 0 THEN usage_volume_MB_network_security ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_network_security_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_realestate_moving <> 0 THEN usage_volume_MB_realestate_moving ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_realestate_moving_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_email <> 0 THEN usage_volume_MB_productivity_email ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_email_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_wireless <> 0 THEN usage_volume_MB_telecom_wireless ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_wireless_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_fleetmanagement <> 0 THEN usage_volume_MB_travel_fleetmanagement ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_fleetmanagement_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_communication_messaging <> 0 THEN usage_volume_MB_communication_messaging ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_communication_messaging_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_gaming_cloud <> 0 THEN usage_volume_MB_gaming_cloud ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_gaming_cloud_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_os_other <> 0 THEN usage_volume_MB_os_other ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_os_other_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_reading <> 0 THEN usage_volume_MB_entertainment_reading ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_reading_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_finance_moneytransfer <> 0 THEN usage_volume_MB_finance_moneytransfer ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_finance_moneytransfer_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_wirelesswirelinesmarthome <> 0 THEN usage_volume_MB_telecom_wirelesswirelinesmarthome ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_wirelesswirelinesmarthome_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_news_politics <> 0 THEN usage_volume_MB_news_politics ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_news_politics_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_smarthome <> 0 THEN usage_volume_MB_telecom_smarthome ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_smarthome_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_softwaredevelopment <> 0 THEN usage_volume_MB_productivity_softwaredevelopment ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_softwaredevelopment_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_lifestyle_kids <> 0 THEN usage_volume_MB_lifestyle_kids ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_lifestyle_kids_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_telecom_benchmark <> 0 THEN usage_volume_MB_telecom_benchmark ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_telecom_benchmark_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_os_update <> 0 THEN usage_volume_MB_os_update ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_os_update_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_communication_calling <> 0 THEN usage_volume_MB_communication_calling ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_communication_calling_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_miscellaneous <> 0 THEN usage_volume_MB_entertainment_miscellaneous ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_miscellaneous_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_network_protocol <> 0 THEN usage_volume_MB_network_protocol ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_network_protocol_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_smarthome_security <> 0 THEN usage_volume_MB_smarthome_security ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_smarthome_security_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_pets_cats <> 0 THEN usage_volume_MB_pets_cats ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_pets_cats_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_news_finance <> 0 THEN usage_volume_MB_news_finance ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_news_finance_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_filetransfer <> 0 THEN usage_volume_MB_productivity_filetransfer ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_filetransfer_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_kids <> 0 THEN usage_volume_MB_entertainment_kids ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_kids_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_finance_investing <> 0 THEN usage_volume_MB_finance_investing ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_finance_investing_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_shopping_food <> 0 THEN usage_volume_MB_shopping_food ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_shopping_food_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_shopping_miscellaneous <> 0 THEN usage_volume_MB_shopping_miscellaneous ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_shopping_miscellaneous_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_network_other <> 0 THEN usage_volume_MB_network_other ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_network_other_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_productivity_storage <> 0 THEN usage_volume_MB_productivity_storage ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_productivity_storage_median,
    PERCENTILE_CONT(CASE WHEN usage_volume_MB_travel_smartcar <> 0 THEN usage_volume_MB_travel_smartcar ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_travel_smartcar_median
    
    
    
    
    --PERCENTILE_CONT(CASE WHEN usage_volume_MB_entertainment_sports <> 0 THEN usage_volume_MB_entertainment_sports ELSE NULL END, 0.5) OVER(PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_sports_median,
    -- ROUND(PERCENT_RANK() OVER (PARTITION BY BRAND_TXT, ts_index ORDER BY usage_volume_MB_entertainment_sports DESC ), 2) AS usage_volume_MB_entertainment_sports_rank,
    --AVG(usage_volume_MB_entertainment_sports) AS avg1,
    --usage_volume_MB_entertainment_sports,
    --AVG(CASE WHEN usage_volume_MB_entertainment_sports <> 0 THEN usage_volume_MB_entertainment_sports ELSE NULL END) OVER (PARTITION BY ts_index, BRAND_TXT) AS usage_volume_MB_entertainment_sports_avg
  FROM brand_table
  --GROUP BY ts_index, start_dt, end_dt, BRAND_TXT
  
)
--SELECT * FROM ranked_data

SELECT  
  ts_index,
  start_dt,
  end_dt,
  BRAND_TXT,
  COUNTIF(usage_volume_MB_entertainment_sports > usage_volume_MB_entertainment_sports_median) AS usage_volume_MB_entertainment_sports_users,
  SUM(usage_volume_MB_entertainment_sports/1000000.0) AS total_entertainment_sports_usage_TB,
  COUNTIF(usage_volume_MB_realestate_landlord > usage_volume_MB_realestate_landlord_median) AS usage_volume_MB_realestate_landlord_users,
  SUM(usage_volume_MB_realestate_landlord/1000000.0) AS total_realestate_landlord_usage_TB,
  COUNTIF(usage_volume_MB_agriculture_farmmanagement > usage_volume_MB_agriculture_farmmanagement_median) AS usage_volume_MB_agriculture_farmmanagement_users,
  SUM(usage_volume_MB_agriculture_farmmanagement/1000000.0) AS total_agriculture_farmmanagement_usage_TB,
  COUNTIF(usage_volume_MB_productivity_education > usage_volume_MB_productivity_education_median) AS usage_volume_MB_productivity_education_users,
  SUM(usage_volume_MB_productivity_education/1000000.0) AS total_productivity_education_usage_TB,
  COUNTIF(usage_volume_MB_telecom_telus > usage_volume_MB_telecom_telus_median) AS usage_volume_MB_telecom_telus_users,
  SUM(usage_volume_MB_telecom_telus/1000000.0) AS total_telecom_telus_usage_TB,
  COUNTIF(usage_volume_MB_realestate_buysellrent > usage_volume_MB_realestate_buysellrent_median) AS usage_volume_MB_realestate_buysellrent_users,
  SUM(usage_volume_MB_realestate_buysellrent/1000000.0) AS total_realestate_buysellrent_usage_TB,
  COUNTIF(usage_volume_MB_travel_trips > usage_volume_MB_travel_trips_median) AS usage_volume_MB_travel_trips_users,
  SUM(usage_volume_MB_travel_trips/1000000.0) AS total_travel_trips_usage_TB,
  COUNTIF(usage_volume_MB_finance_banking > usage_volume_MB_finance_banking_median) AS usage_volume_MB_finance_banking_users,
  SUM(usage_volume_MB_finance_banking/1000000.0) AS total_finance_banking_usage_TB,
  COUNTIF(usage_volume_MB_pets_dogs > usage_volume_MB_pets_dogs_median) AS usage_volume_MB_pets_dogs_users,
  SUM(usage_volume_MB_pets_dogs/1000000.0) AS total_pets_dogs_usage_TB,
  COUNTIF(usage_volume_MB_lifestyle_mentalhealth > usage_volume_MB_lifestyle_mentalhealth_median) AS usage_volume_MB_lifestyle_mentalhealth_users,
  SUM(usage_volume_MB_lifestyle_mentalhealth/1000000.0) AS total_lifestyle_mentalhealth_usage_TB,
  COUNTIF(usage_volume_MB_os_appstore > usage_volume_MB_os_appstore_median) AS usage_volume_MB_os_appstore_users,
  SUM(usage_volume_MB_os_appstore/1000000.0) AS total_os_appstore_usage_TB,
  COUNTIF(usage_volume_MB_news_generic > usage_volume_MB_news_generic_median) AS usage_volume_MB_news_generic_users,
  SUM(usage_volume_MB_news_generic/1000000.0) AS total_news_generic_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_music > usage_volume_MB_entertainment_music_median) AS usage_volume_MB_entertainment_music_users,
  SUM(usage_volume_MB_entertainment_music/1000000.0) AS total_entertainment_music_usage_TB,
  COUNTIF(usage_volume_MB_communication_miscellaneous > usage_volume_MB_communication_miscellaneous_median) AS usage_volume_MB_communication_miscellaneous_users,
  SUM(usage_volume_MB_communication_miscellaneous/1000000.0) AS total_communication_miscellaneous_usage_TB,
  COUNTIF(usage_volume_MB_gaming_moderate > usage_volume_MB_gaming_moderate_median) AS usage_volume_MB_gaming_moderate_users,
  SUM(usage_volume_MB_gaming_moderate/1000000.0) AS total_gaming_moderate_usage_TB,
  COUNTIF(usage_volume_MB_utility_security > usage_volume_MB_utility_security_median) AS usage_volume_MB_utility_security_users,
  SUM(usage_volume_MB_utility_security/1000000.0) AS total_utility_security_usage_TB,
  COUNTIF(usage_volume_MB_communication_socialmedia > usage_volume_MB_communication_socialmedia_median) AS usage_volume_MB_communication_socialmedia_users,
  SUM(usage_volume_MB_communication_socialmedia/1000000.0) AS total_communication_socialmedia_usage_TB,
  COUNTIF(usage_volume_MB_productivity_other > usage_volume_MB_productivity_other_median) AS usage_volume_MB_productivity_other_users,
  SUM(usage_volume_MB_productivity_other/1000000.0) AS total_productivity_other_usage_TB,
  COUNTIF(usage_volume_MB_shopping_fashion > usage_volume_MB_shopping_fashion_median) AS usage_volume_MB_shopping_fashion_users,
  SUM(usage_volume_MB_shopping_fashion/1000000.0) AS total_shopping_fashion_usage_TB,
  COUNTIF(usage_volume_MB_productivity_webbrowser > usage_volume_MB_productivity_webbrowser_median) AS usage_volume_MB_productivity_webbrowser_users,
  SUM(usage_volume_MB_productivity_webbrowser/1000000.0) AS total_productivity_webbrowser_usage_TB,
  COUNTIF(usage_volume_MB_finance_utilities > usage_volume_MB_finance_utilities_median) AS usage_volume_MB_finance_utilities_users,
  SUM(usage_volume_MB_finance_utilities/1000000.0) AS total_finance_utilities_usage_TB,
  COUNTIF(usage_volume_MB_travel_travel > usage_volume_MB_travel_travel_median) AS usage_volume_MB_travel_travel_users,
  SUM(usage_volume_MB_travel_travel/1000000.0) AS total_travel_travel_usage_TB,
  COUNTIF(usage_volume_MB_lifestyle_fitness > usage_volume_MB_lifestyle_fitness_median) AS usage_volume_MB_lifestyle_fitness_users,
  SUM(usage_volume_MB_lifestyle_fitness/1000000.0) AS total_lifestyle_fitness_usage_TB,
  COUNTIF(usage_volume_MB_finance_business > usage_volume_MB_finance_business_median) AS usage_volume_MB_finance_business_users,
  SUM(usage_volume_MB_finance_business/1000000.0) AS total_finance_business_usage_TB,
  COUNTIF(usage_volume_MB_lifestyle_relationships > usage_volume_MB_lifestyle_relationships_median) AS usage_volume_MB_lifestyle_relationships_users,
  SUM(usage_volume_MB_lifestyle_relationships/1000000.0) AS total_lifestyle_relationships_usage_TB,
  COUNTIF(usage_volume_MB_telecom_wireline > usage_volume_MB_telecom_wireline_median) AS usage_volume_MB_telecom_wireline_users,
  SUM(usage_volume_MB_telecom_wireline/1000000.0) AS total_telecom_wireline_usage_TB,
  COUNTIF(usage_volume_MB_travel_lodging > usage_volume_MB_travel_lodging_median) AS usage_volume_MB_travel_lodging_users,
  SUM(usage_volume_MB_travel_lodging/1000000.0) AS total_travel_lodging_usage_TB,
  COUNTIF(usage_volume_MB_productivity_editingsoftware > usage_volume_MB_productivity_editingsoftware_median) AS usage_volume_MB_productivity_editingsoftware_users,
  SUM(usage_volume_MB_productivity_editingsoftware/1000000.0) AS total_productivity_editingsoftware_usage_TB,
  COUNTIF(usage_volume_MB_pets_petssupplies > usage_volume_MB_pets_petssupplies_median) AS usage_volume_MB_pets_petssupplies_users,
  SUM(usage_volume_MB_pets_petssupplies/1000000.0) AS total_pets_petssupplies_usage_TB,
  COUNTIF(usage_volume_MB_travel_ridehailing > usage_volume_MB_travel_ridehailing_median) AS usage_volume_MB_travel_ridehailing_users,
  SUM(usage_volume_MB_travel_ridehailing/1000000.0) AS total_travel_ridehailing_usage_TB,
  COUNTIF(usage_volume_MB_agriculture_farmassociations > usage_volume_MB_agriculture_farmassociations_median) AS usage_volume_MB_agriculture_farmassociations_users,
  SUM(usage_volume_MB_agriculture_farmassociations/1000000.0) AS total_agriculture_farmassociations_usage_TB,
  COUNTIF(usage_volume_MB_productivity_professional > usage_volume_MB_productivity_professional_median) AS usage_volume_MB_productivity_professional_users,
  SUM(usage_volume_MB_productivity_professional/1000000.0) AS total_productivity_professional_usage_TB,
  COUNTIF(usage_volume_MB_smarthome_automation > usage_volume_MB_smarthome_automation_median) AS usage_volume_MB_smarthome_automation_users,
  SUM(usage_volume_MB_smarthome_automation/1000000.0) AS total_smarthome_automation_usage_TB,
  COUNTIF(usage_volume_MB_lifestyle_healthcare > usage_volume_MB_lifestyle_healthcare_median) AS usage_volume_MB_lifestyle_healthcare_users,
  SUM(usage_volume_MB_lifestyle_healthcare/1000000.0) AS total_lifestyle_healthcare_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_tvandmovies > usage_volume_MB_entertainment_tvandmovies_median) AS usage_volume_MB_entertainment_tvandmovies_users,
  SUM(usage_volume_MB_entertainment_tvandmovies/1000000.0) AS total_entertainment_tvandmovies_usage_TB,
  COUNTIF(usage_volume_MB_travel_flights > usage_volume_MB_travel_flights_median) AS usage_volume_MB_travel_flights_users,
  SUM(usage_volume_MB_travel_flights/1000000.0) AS total_travel_flights_usage_TB,
  COUNTIF(usage_volume_MB_gaming_casual > usage_volume_MB_gaming_casual_median) AS usage_volume_MB_gaming_casual_users,
  SUM(usage_volume_MB_gaming_casual/1000000.0) AS total_gaming_casual_usage_TB,
  COUNTIF(usage_volume_MB_finance_paymentapps > usage_volume_MB_finance_paymentapps_median) AS usage_volume_MB_finance_paymentapps_users,
  SUM(usage_volume_MB_finance_paymentapps/1000000.0) AS total_finance_paymentapps_usage_TB,
  COUNTIF(usage_volume_MB_gaming_kids > usage_volume_MB_gaming_kids_median) AS usage_volume_MB_gaming_kids_users,
  SUM(usage_volume_MB_gaming_kids/1000000.0) AS total_gaming_kids_usage_TB,
  COUNTIF(usage_volume_MB_travel_navigation > usage_volume_MB_travel_navigation_median) AS usage_volume_MB_travel_navigation_users,
  SUM(usage_volume_MB_travel_navigation/1000000.0) AS total_travel_navigation_usage_TB,
  COUNTIF(usage_volume_MB_utility_devicecare > usage_volume_MB_utility_devicecare_median) AS usage_volume_MB_utility_devicecare_users,
  SUM(usage_volume_MB_utility_devicecare/1000000.0) AS total_utility_devicecare_usage_TB,
  COUNTIF(usage_volume_MB_telecom_wirelesswireline > usage_volume_MB_telecom_wirelesswireline_median) AS usage_volume_MB_telecom_wirelesswireline_users,
  SUM(usage_volume_MB_telecom_wirelesswireline/1000000.0) AS total_telecom_wirelesswireline_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_news > usage_volume_MB_entertainment_news_median) AS usage_volume_MB_entertainment_news_users,
  SUM(usage_volume_MB_entertainment_news/1000000.0) AS total_entertainment_news_usage_TB,
  COUNTIF(usage_volume_MB_telecom_others > usage_volume_MB_telecom_others_median) AS usage_volume_MB_telecom_others_users,
  SUM(usage_volume_MB_telecom_others/1000000.0) AS total_telecom_others_usage_TB,
  COUNTIF(usage_volume_MB_news_weather > usage_volume_MB_news_weather_median) AS usage_volume_MB_news_weather_users,
  SUM(usage_volume_MB_news_weather/1000000.0) AS total_news_weather_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_radio > usage_volume_MB_entertainment_radio_median) AS usage_volume_MB_entertainment_radio_users,
  SUM(usage_volume_MB_entertainment_radio/1000000.0) AS total_entertainment_radio_usage_TB,
  COUNTIF(usage_volume_MB_travel_airport > usage_volume_MB_travel_airport_median) AS usage_volume_MB_travel_airport_users,
  SUM(usage_volume_MB_travel_airport/1000000.0) AS total_travel_airport_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_live > usage_volume_MB_entertainment_live_median) AS usage_volume_MB_entertainment_live_users,
  SUM(usage_volume_MB_entertainment_live/1000000.0) AS total_entertainment_live_usage_TB,
  COUNTIF(usage_volume_MB_telecom_pricecomparison > usage_volume_MB_telecom_pricecomparison_median) AS usage_volume_MB_telecom_pricecomparison_users,
  SUM(usage_volume_MB_telecom_pricecomparison/1000000.0) AS total_telecom_pricecomparison_usage_TB,
  COUNTIF(usage_volume_MB_pets_other > usage_volume_MB_pets_other_median) AS usage_volume_MB_pets_other_users,
  SUM(usage_volume_MB_pets_other/1000000.0) AS total_pets_other_usage_TB,
  COUNTIF(usage_volume_MB_lifestyle_identification > usage_volume_MB_lifestyle_identification_median) AS usage_volume_MB_lifestyle_identification_users,
  SUM(usage_volume_MB_lifestyle_identification/1000000.0) AS total_lifestyle_identification_usage_TB,
  COUNTIF(usage_volume_MB_realestate_projectmanagement > usage_volume_MB_realestate_projectmanagement_median) AS usage_volume_MB_realestate_projectmanagement_users,
  SUM(usage_volume_MB_realestate_projectmanagement/1000000.0) AS total_realestate_projectmanagement_usage_TB,
  COUNTIF(usage_volume_MB_communication_talking > usage_volume_MB_communication_talking_median) AS usage_volume_MB_communication_talking_users,
  SUM(usage_volume_MB_communication_talking/1000000.0) AS total_communication_talking_usage_TB,
  COUNTIF(usage_volume_MB_network_security > usage_volume_MB_network_security_median) AS usage_volume_MB_network_security_users,
  SUM(usage_volume_MB_network_security/1000000.0) AS total_network_security_usage_TB,
  COUNTIF(usage_volume_MB_realestate_moving > usage_volume_MB_realestate_moving_median) AS usage_volume_MB_realestate_moving_users,
  SUM(usage_volume_MB_realestate_moving/1000000.0) AS total_realestate_moving_usage_TB,
  COUNTIF(usage_volume_MB_productivity_email > usage_volume_MB_productivity_email_median) AS usage_volume_MB_productivity_email_users,
  SUM(usage_volume_MB_productivity_email/1000000.0) AS total_productivity_email_usage_TB,
  COUNTIF(usage_volume_MB_telecom_wireless > usage_volume_MB_telecom_wireless_median) AS usage_volume_MB_telecom_wireless_users,
  SUM(usage_volume_MB_telecom_wireless/1000000.0) AS total_telecom_wireless_usage_TB,
  COUNTIF(usage_volume_MB_travel_fleetmanagement > usage_volume_MB_travel_fleetmanagement_median) AS usage_volume_MB_travel_fleetmanagement_users,
  SUM(usage_volume_MB_travel_fleetmanagement/1000000.0) AS total_travel_fleetmanagement_usage_TB,
  COUNTIF(usage_volume_MB_communication_messaging > usage_volume_MB_communication_messaging_median) AS usage_volume_MB_communication_messaging_users,
  SUM(usage_volume_MB_communication_messaging/1000000.0) AS total_communication_messaging_usage_TB,
  COUNTIF(usage_volume_MB_gaming_cloud > usage_volume_MB_gaming_cloud_median) AS usage_volume_MB_gaming_cloud_users,
  SUM(usage_volume_MB_gaming_cloud/1000000.0) AS total_gaming_cloud_usage_TB,
  COUNTIF(usage_volume_MB_os_other > usage_volume_MB_os_other_median) AS usage_volume_MB_os_other_users,
  SUM(usage_volume_MB_os_other/1000000.0) AS total_os_other_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_reading > usage_volume_MB_entertainment_reading_median) AS usage_volume_MB_entertainment_reading_users,
  SUM(usage_volume_MB_entertainment_reading/1000000.0) AS total_entertainment_reading_usage_TB,
  COUNTIF(usage_volume_MB_finance_moneytransfer > usage_volume_MB_finance_moneytransfer_median) AS usage_volume_MB_finance_moneytransfer_users,
  SUM(usage_volume_MB_finance_moneytransfer/1000000.0) AS total_finance_moneytransfer_usage_TB,
  COUNTIF(usage_volume_MB_telecom_wirelesswirelinesmarthome > usage_volume_MB_telecom_wirelesswirelinesmarthome_median) AS usage_volume_MB_telecom_wirelesswirelinesmarthome_users,
  SUM(usage_volume_MB_telecom_wirelesswirelinesmarthome/1000000.0) AS total_telecom_wirelesswirelinesmarthome_usage_TB,
  COUNTIF(usage_volume_MB_news_politics > usage_volume_MB_news_politics_median) AS usage_volume_MB_news_politics_users,
  SUM(usage_volume_MB_news_politics/1000000.0) AS total_news_politics_usage_TB,
  COUNTIF(usage_volume_MB_telecom_smarthome > usage_volume_MB_telecom_smarthome_median) AS usage_volume_MB_telecom_smarthome_users,
  SUM(usage_volume_MB_telecom_smarthome/1000000.0) AS total_telecom_smarthome_usage_TB,
  COUNTIF(usage_volume_MB_productivity_softwaredevelopment > usage_volume_MB_productivity_softwaredevelopment_median) AS usage_volume_MB_productivity_softwaredevelopment_users,
  SUM(usage_volume_MB_productivity_softwaredevelopment/1000000.0) AS total_productivity_softwaredevelopment_usage_TB,
  COUNTIF(usage_volume_MB_lifestyle_kids > usage_volume_MB_lifestyle_kids_median) AS usage_volume_MB_lifestyle_kids_users,
  SUM(usage_volume_MB_lifestyle_kids/1000000.0) AS total_lifestyle_kids_usage_TB,
  COUNTIF(usage_volume_MB_telecom_benchmark > usage_volume_MB_telecom_benchmark_median) AS usage_volume_MB_telecom_benchmark_users,
  SUM(usage_volume_MB_telecom_benchmark/1000000.0) AS total_telecom_benchmark_usage_TB,
  COUNTIF(usage_volume_MB_os_update > usage_volume_MB_os_update_median) AS usage_volume_MB_os_update_users,
  SUM(usage_volume_MB_os_update/1000000.0) AS total_os_update_usage_TB,
  COUNTIF(usage_volume_MB_communication_calling > usage_volume_MB_communication_calling_median) AS usage_volume_MB_communication_calling_users,
  SUM(usage_volume_MB_communication_calling/1000000.0) AS total_communication_calling_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_miscellaneous > usage_volume_MB_entertainment_miscellaneous_median) AS usage_volume_MB_entertainment_miscellaneous_users,
  SUM(usage_volume_MB_entertainment_miscellaneous/1000000.0) AS total_entertainment_miscellaneous_usage_TB,
  COUNTIF(usage_volume_MB_network_protocol > usage_volume_MB_network_protocol_median) AS usage_volume_MB_network_protocol_users,
  SUM(usage_volume_MB_network_protocol/1000000.0) AS total_network_protocol_usage_TB,
  COUNTIF(usage_volume_MB_smarthome_security > usage_volume_MB_smarthome_security_median) AS usage_volume_MB_smarthome_security_users,
  SUM(usage_volume_MB_smarthome_security/1000000.0) AS total_smarthome_security_usage_TB,
  COUNTIF(usage_volume_MB_pets_cats > usage_volume_MB_pets_cats_median) AS usage_volume_MB_pets_cats_users,
  SUM(usage_volume_MB_pets_cats/1000000.0) AS total_pets_cats_usage_TB,
  COUNTIF(usage_volume_MB_news_finance > usage_volume_MB_news_finance_median) AS usage_volume_MB_news_finance_users,
  SUM(usage_volume_MB_news_finance/1000000.0) AS total_news_finance_usage_TB,
  COUNTIF(usage_volume_MB_productivity_filetransfer > usage_volume_MB_productivity_filetransfer_median) AS usage_volume_MB_productivity_filetransfer_users,
  SUM(usage_volume_MB_productivity_filetransfer/1000000.0) AS total_productivity_filetransfer_usage_TB,
  COUNTIF(usage_volume_MB_entertainment_kids > usage_volume_MB_entertainment_kids_median) AS usage_volume_MB_entertainment_kids_users,
  SUM(usage_volume_MB_entertainment_kids/1000000.0) AS total_entertainment_kids_usage_TB,
  COUNTIF(usage_volume_MB_finance_investing > usage_volume_MB_finance_investing_median) AS usage_volume_MB_finance_investing_users,
  SUM(usage_volume_MB_finance_investing/1000000.0) AS total_finance_investing_usage_TB,
  COUNTIF(usage_volume_MB_shopping_food > usage_volume_MB_shopping_food_median) AS usage_volume_MB_shopping_food_users,
  SUM(usage_volume_MB_shopping_food/1000000.0) AS total_shopping_food_usage_TB,
  COUNTIF(usage_volume_MB_shopping_miscellaneous > usage_volume_MB_shopping_miscellaneous_median) AS usage_volume_MB_shopping_miscellaneous_users,
  SUM(usage_volume_MB_shopping_miscellaneous/1000000.0) AS total_shopping_miscellaneous_usage_TB,
  COUNTIF(usage_volume_MB_network_other > usage_volume_MB_network_other_median) AS usage_volume_MB_network_other_users,
  SUM(usage_volume_MB_network_other/1000000.0) AS total_network_other_usage_TB,
  COUNTIF(usage_volume_MB_productivity_storage > usage_volume_MB_productivity_storage_median) AS usage_volume_MB_productivity_storage_users,
  SUM(usage_volume_MB_productivity_storage/1000000.0) AS total_productivity_storage_usage_TB,
  COUNTIF(usage_volume_MB_travel_smartcar > usage_volume_MB_travel_smartcar_median) AS usage_volume_MB_travel_smartcar_users,
  SUM(usage_volume_MB_travel_smartcar/1000000.0) AS total_travel_smartcar_usage_TB,
FROM ranked_data
GROUP BY ts_index,start_dt, end_dt, BRAND_TXT
ORDER BY ts_index